export { default as useGetBooks } from './getBooks.js'
export { default as useDetailBook } from './detailBook.js'
export { default as useCreateBook } from './createBook.js'
export { default as useDeleteBook } from './deleteBook.js'
export { default as useEditBook } from './editBook.js'